# Change these first
owner: ainize-team # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: AI Network
    url: https://ainetwork.ai
  - name: Ainize
    url: https://ainize.ai
  - name: aFan (JP)
    url: https://afan.ai/ja
  - name: Common Computer
    url: https://comcom.ai

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Status
  introTitle: "Uptime and Status."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
